name: CI - Deploy
on:
  workflow_run:
    workflows: ["CI - Tests"]
    branches:
      - develop
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build image Docker (production)
        run: |
          docker build \
          -t ms-customers_latest \
          -f ms-customers/Dockerfile \
          ms-customers

      - name: Verification de l'image
        run: |
          docker images | grep ms-customers
